language: java
notifications:
  slack:
    rooms:
      secure: mpAuO1pUX1ucr2jozx9hB89PKiQYrQNM2XGxlScgd0PndpKrLrh/KQgguAQk53ZVSgI1GLnBmC3/ONqWqHrM7n1LipgKBcQoNQCSvfrUR0nc5sA2piB7pY49Dh6M9qGBWGwZYsEGWz4yHasLqUOByMThiSZhPKQkMDZ0ZMTzRmWQ3yrBzDtin0MvKLYJTWV72qLbBZLtpa2nH65HhRVYX90kV2YSCcUvH3Ysm2uiavQV6FqJHXnXC67g5QjLK//b/+ddnYwNphgjyC4c7DjlbKlwZYeOD58ZbcPvQ/XrNyp6HnW1BrLoX9tVTu4I7A2rG6PWuP4Y9XwU2w/jHOgQgBiUgd2ff2KVYVSl/hJC81LQ+1hrmYFu0IAARv8MCMXs5I+8w4bTw9sevKdUPinrPhIYcNxoMNF2M4XERLUw/bKCyTXktfgruvGgsREthmPp+hsJqGaM2EOE6+o30LAw/FwAZUVhB/RFqRjvyeD4jw9XAx0CalECKrRb4/BLHhLvXOSRbG02R7F+hDu1tYt/Pxc9pQLsaURwEIiX9f3biDYgd/pw1ycZ+85Bf0KLXSrZLf7tIrfmsy5Jjkf2aSbfPHaGZEZ2An9hahByhDYHZk56UeWUdcl8FyB9x/H1iplm7S/nIVfc1cgyn/nKqyzN4eHUuqtUVgn1og/k3dtT5X0=
deploy:
  provider: releases
  api_key:
    secure: th1KxFkdH2Cwndn1/N7quP0Nzb7FPYryfSSKSpMLU/oAz+9Ak2EXSaDYoOXAgFi7pUxafxaCBXs3U9x3NDQvC2JZqz3koblzYQL0MIRYjL5Ckez1XJ8qCrk2aXVoyTyRnqBmvqmmswTBQQ+h8Ob7ASMY+7UX/2OO/eeeeIGReoq7I6p0l+d4u+kV3yVjQXAxJn9ZQCo06sXU5FEwY135uK7lNkv0GgaCUVH7Yw9oOnQT7eqmQsvJEgKmQCnsSY4l829mHX10dbNfBZ/oLhW3Ok9WoX45iYQM686249MB8sObPCxdYNoHi5Y2IJzQXL4Ei4bzk++aiczuh680TlRPHD9rlaowNSmj303vRRE19UlB4yRKll7pVvjtRbrsvbUYgDLdXcuhEhg56GWSRdWX3UzrcHHo3RdQ0ErTG+FnImiuIto/WeMwVYj7cemHm5l0CB2GQIbeUVA31qN8HeRk+uvJpMwp2RCSoB0/pjB0mEyKcfFYc6K4lPMNlIAZGdxi4PqcEhyaS2SZhSpfgdwJ/WIsDaKQvFs4TBVCoKkn1awCNsIA074W2SUMBfBScNKNPZvav99XM573iazhMSihMUBrqRwcG3q3Auf8uy2AMUd3LLLTw06KtjqOMB3udgA8zOV01bnl8Z9AhfWkjHD9D8zkSxPp68ynZ7/wAHO36LQ=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-chaos-monkey-plugin